export const CREATE_NEW_PROJECT = 'project/CREATE_NEW_PROJECT'
export const ADD_NEW_CONSUMER = 'project/ADD_NEW_CONSUMER'
export const ADD_NEW_SUPPLIER = 'project/ADD_NEW_SUPPLIER'
export const ADD_NEW_PRODUCER = 'project/ADD_NEW_PRODUCER'
export const SET_PRODUCERS = 'project/SET_PRODUCERS'
export const ADD_NEW_NETWORK = 'project/ADD_NEW_NETWORK'
export const SET_INITIAL_STATE = 'project/SET_INITIAL_STATE'